context:
  version: 0.7.0

package:
  name: uutils-findutils
  version: ${{ version }}

source:
  url: https://github.com/uutils/findutils/archive/${{ version }}.tar.gz
  sha256: 129c263c6953b5c6aa756666aa9f5e968e04c1d0315d9d8ad9e93ec3d1823bc0

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - oniguruma

tests:
  - script:
      - find --help
      - xargs --help 2>&1 | grep -q "Usage: xargs"

about:
  license: MIT
  license_file: LICENSE
  summary: Cross-platform Rust rewrite of the GNU findutils
  homepage: https://github.com/uutils/findutils
  repository: https://github.com/uutils/findutils

extra:
  recipe-maintainers:
    - danielnachun
